### PR TITLE
Fetch_interfaces

### PR DESCRIPTION
**Pull request by jmanteau**
Add a fetch_interfaces method with two possibilities. Extended take twice the time on my setup.

### CODE REVIEW

**Comment by jeremyschulman** [comment]
@jmanteau - any chance you have time to discuss next week?  I'd like to ensure your use-case is supported.

**Comment by jeremyschulman** [comment]
@jmanteau - I am hoping that you've had a chance to review my prior comment.  Please let me know if you are satisfied with the current approach/answer.  I will plan to close this PR in one week if I have not heard anything further from you.  Thank you.

**Comment by jmanteau** [comment]
I'm currently on medical leave. I'll not test this before next year. You can close it if you want, I'll check when I'll be back.

**Comment by jeremyschulman** [comment]
@jmanteau - I hope all goes well!  Let us reconnected in the new year.

**Pull request closed without merging**
